### ISSUE TITLE
 device.commit_config()

### ISSUE THREAD

**Issue by jurajbgh** [napalm-automation/napalm-ansible#112]
Hi all,
Im working with Napalm with python and Im executing the following lines.  This is a Cisco-xe. (ref link http://networktocode.com/labs/tutorials/how-to-use-napalm-python-library-to-manage-ios-devices/)

from napalm import get_network_driver
driver = get_network_driver('ios')
device = driver('csr1', 'ntc', 'ntc123')
device.open() 
device.load_replace_candidate(filename='newconfig.cfg')
device.commit_config()

After I commit I get the following error
device.commit_config()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 447, in commit_config
    raise ReplaceConfigException(msg)
napalm.base.exceptions.ReplaceConfigException: Candidate config could not be applied
  
  
  
Failed to apply command Last configuration change at 13:41:24 UTC Thu Jan 18 2018
Aborting Rollback.

Rollback failed.Reverting back to the original configuration: bootflash:archive-Jan-18-17-54-15.366-0 ...
 
Total number of passes: 1
Rollback Done

The original configuration has been successfully restored.

Thanks.

**Comment by ktbyers** [comment]
@jurajbgh It sounds like you have something in your new configuration that is not valid. 

Have you checked your `flash:/candiate_config.txt` file? Have you manually tried to execute:

```
configure replace flash:/candidate_config.txt force revert trigger error
```

I would start with a single config line change (for example change the 'logging buffer 5000' or something simple).

Note, you need to start with a full configuration file. Your starting configuration file will probably need to be copied off the box using an SSH channel (otherwise you will likely have issues with the self-signed certificate).

Just update issue here with what you find.

**Comment by jurajbgh** [comment]
@ktbyers
I just did the same test with only a few lines, but when I do the commit _config I dont see and change.

hostname CMT1.ROC1-CBR8
!
interface GigabitEthernet2
ip add 10.10.10.1 255.255.255.0
!

Thanks.

**Comment by ktbyers** [comment]
@jurajbgh Are your changes in the file, flash:/candidate_config.txt (note, might possibly be a different filesystem like bootflash: depending on the device)?

What happens if you manually do the `configure replace` referenced above--does it work properly?


Kirk

**Comment by jurajbgh** [comment]
@ktbyers Im working with cisco-xe and I know that napalm is for IOS or XR, but I manage to make this work, the only thing I need help is how i can send via python the command "copy bootflash:txt run"
thanks.!

**Comment by ktbyers** [comment]
NAPALM-IOS supports both IOS and IOS-XE so the standard NAPALM methods should work (which is why I asked what happens when you manually do `configure replace` as that is what NAPALM's replace operation will do).

**Comment by jurajbgh** [comment]
@ktbyers Im working with the XE version I tested the replace and is not working is because I was adding more line cards that the device had. but when I do the merge I get this "scp.SCPException: Privilege denied." I have privilege 15 and ip scp server is enabled.  If i have enable secret configure I should i configure the validation? 
thanks.

**Comment by ktbyers** [comment]
@jurajbgh I think Cisco IOS/IOS-XE requires you to use a `privlege level 15` account in order to SCP (i.e. the SCP itself requires priv 15 and there is no way to enable it...since it is Secure Copy).

There are two workarounds for this:
1. Use an account that logs in at priv 15 (i.e. is already priv 15 without any enable).
2. Use an inline_transfer which doesn't use Secure Copy, but instead transfers entirely inside the SSH session (using TCL file transfer).

In order to use inline_transfer you would need to do, something like:

```
provider:
  hostname: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  dev_os: "ios"
  optional_args:
    secret: "{{ password }}"
    inline_transfer: True
```

Hope that helps.
