### ISSUE TITLE
Is there a rollback option available in napalm_install_config?

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ansible#98]
I quickly checked and didn't see one.

**Comment by dbarrosop** [comment]
I think it should probably be a dedicated module so you can do something like:
```
- napalm_install_config:
- block:
    - test 1
    - test 2
    - test N
  rescue: # some test failed
    - napalm_rollback
```

**Comment by tejat454** [comment]
Hi Team,

napalm-ansible is very good for network automation. I personally like napalm modules in python and I play very well with them without any issues. But I don't find a rollback method in napalm-ansible, anything on roadmap to incorporate rollback method in ansible module?

I'm using block and rescue method but unable to orchestrate well due to missing rollback module when my post validation on device fails.

If there is method already for rollback then please suggest me.

Once again, thanks for you guys for your tireless efforts to make multi-vendor network automation easy with NAPALM.

I blog on napalm here:  http://www.mytechconsult.com/?p=120

Regards,
Tej

**Comment by ktbyers** [comment]
@tejat454 Yes, we will probably implement something here as well as a commit confirmed feature.  I don't have a timeline on this though.

NAPALM does have an existing rollback method, we just haven't implemented an Ansible module that allows it to be used.

**Comment by ktbyers** [comment]
Closing as this is a duplicate of a new issue I created.
